version: "3.9"

services:
  server:
    container_name: "${PROJECT_NAME}-todolist"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: .
        target: /var/www/app/todolist
    ports:
      - target: 8642
        published: ${SERVER_PORT:-8642}
        protocol: tcp
        mode: host
    depends_on:
      - db
  telegram_bot_todolist:
    container_name: "${PROJECT_NAME}-telegram-bot-todolist"
    build:
      context: .
      dockerfile: ../go-telegram-bot-todolist/Dockerfile
    volumes:
      - type: bind
        source: ../go-telegram-bot-todolist
        target: /var/www/app/go-telegram-bot-todolist
    ports:
      - target: 7531
        published: ${TELEGRAM_PORT:-7531}
        protocol: tcp
        mode: host
    depends_on:
      - db
  db:
    container_name: "${PROJECT_NAME}-db"
    image: mysql:8.0
    ports:
      - target: 3306
        published: ${DB_PORT:-3306}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_NAME:-golang_db}
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASS:-password}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-password}
  redis:
    container_name: "${PROJECT_NAME}-redis"
    image: redis:6.2
    ports:
      - target: 6379
        published: ${REDIS_PORT:-6379}
        protocol: tcp
        mode: host
volumes:
  db-store:
